version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: jinen-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: jinen
    ports:
      - '27017:27017'
    volumes:
      - jinen-database:/var/lib/mongo/data
    networks:
      - jinen-network

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: jinen-docs-development
    restart: always
    ports:
      - '3000:80'
    networks:
      - jinen-network

  cms:
    build:
      context: .
      dockerfile: Dockerfile.cms
    container_name: jinen-cms-development
    restart: always
    environment:
      NODE_ENV: development
      PAYLOAD_SERVER_PORT: 3001
      PAYLOAD_SERVER_URL: http://localhost:3001
      PAYLOAD_CONFIG_SECRET: my-secret
      PAYLOAD_CONFIG_PATH: dist/payload-config.js
      MONGODB_URI: mongodb://user:root@mongo:27017/?authMechanism=DEFAULT
    ports:
      - '3001:3001'
    volumes:
      - jinen-cms-media:/app/media
      - jinen-cms-node_modules:/app/node_modules
    networks:
      - jinen-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: jinen-web-development
    restart: always
    environment:
      PUBLIC_CMS_URL: http://cms:3001
    depends_on:
      - cms
    ports:
      - '3002:3002'
    networks:
      - jinen-network

volumes:
  jinen-database:
    name: jinen-database
  jinen-cms-media:
    name: jinen-cms-media
  jinen-cms-node_modules:
    name: jinen-cms-node_modules

networks:
  jinen-network:
    name: jinen-network
    driver: bridge
