FROM node:20-alpine as base

# ;---------------;
# ; Builder stage ;
# ;---------------;
FROM base as builder

WORKDIR /app

RUN npm i -g pnpm

COPY .npmrc package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY . .

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile && \
    pnpm --filter web build

# ;--------------;
# ; Runner stage ;
# ;--------------;
FROM base as runner

WORKDIR /app

COPY --from=builder /app/.npmrc /app/package.json /app/pnpm-lock.yaml /app/pnpm-workspace.yaml ./
COPY --from=builder /app/node_modules ./node_modules/
COPY --from=builder /app/apps/web ./apps/web/

ENV NODE_ENV=production

EXPOSE 3002

CMD ["node", "apps/web/build/index.js"]
