FROM node:20-alpine as base

# ;-------------;
# ; Build stage ;
# ;-------------;
FROM base as builder

WORKDIR /app

RUN npm i -g pnpm

COPY . .

RUN --mount=type=cache,id=pnpm-store,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile && \
    pnpm web:build && \
    pnpm prune --prod

# ;---------------;
# ; Runtime stage ;
# ;---------------;
FROM base as runtime

WORKDIR /app

COPY --from=builder /app/apps/web/package.json /app/apps/web/build ./build/

ENV PORT=3002

EXPOSE 3002

CMD ["node", "build/index.js"]
