name: 🐞 Bug
description: Reportar un bug en el proyecto
title: '[JINEN-BUG] Introduzca un breve resumen del bug'
labels: ['🐞 bug', '⚕️ triage']
body:
  - type: checkboxes
    id: search-issues
    attributes:
      label: ¿Existe algún issue para esto?
      description: Por favor, busque en la pestaña de issues para verificar si ya existe uno para la característica que está solicitando.
      options:
        - label: He buscado en los issues existentes.
          required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Describa el problema que está experimentando
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Describa el comportamiento esperado
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Proporcione un enlace a una reproducción mínima del problema
      value: '[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/JinenGroup/platform-next)'
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Proporcione el entorno en el que descubrió el problema
      multiple: true
      options:
        - Desarrollo
        - Producción
    validations:
      required: true

  - type: dropdown
    id: application
    attributes:
      label: Proporcione la aplicación en la que descubrió el problema
      multiple: true
      options:
        - Docs
        - Cms
        - Web

  - type: dropdown
    id: browser
    attributes:
      label: Seleccione los navegadores en los que está experimentando el problema.
      multiple: true
      options:
        - Firefox
        - Brave
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copie y pegue cualquier log relevante.
      render: shell
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Contexto adicional
      placeholder: Proporcione cualquier contexto adicional sobre el problema que está experimentando. Si es posible, incluya capturas de pantalla.
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: ¿Le gustaría realizar un pull-request para corregir el Bug?
      options:
        - 'Sí 🚀'
        - 'No'
    validations:
      required: true
