name: 游댠 Feature
description: Sugerir una idea para el proyecto
title: '[JINEN-FEATURE] Introduzca un breve resumen de la caracter칤stica'
labels: ['游댠 feature', '丘됊잺 triage']
body:
  - type: checkboxes
    attributes:
      label: 쮼xiste alg칰n issue para esto?
      description: Por favor, busque en la pesta침a de issues para verificar si ya existe uno para la caracter칤stica que est치 solicitando.
      options:
        - label: He buscado en los issues existentes
          required: true

  - type: textarea
    id: feature-behavior
    attributes:
      label: Describa el problema que resuelve su solicitud
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describa la soluci칩n que desea
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Contexto adicional
      placeholder: Proporcione cualquier enlace o referencia que nos d칠 m치s contexto sobre el problema que est치 experimentando.
    validations:
      required: false