name: 游댠 Feature
description: Sugerir una idea para el proyecto
title: '[JINEN-FEATURE] Introduzca un breve resumen de la caracter칤stica'
labels: ['feature', 'triage']
body:
  - type: checkboxes
    attributes:
      label: 쮼xiste alg칰n issue existente para esto?
      description: Por favor, busque en la pesta침a de issues para ver si ya existe uno para la caracter칤stica que est치 solicitando.
      options:
        - label: He buscado en los issues existentes.
          required: true

  - type: textarea
    id: feature-behavior
    attributes:
      label: Describa el problema que resuelve su solicitud.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describa la soluci칩n que desea.
      render: markdown
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Contexto adicional
      placeholder: Proporcione cualquier enlace o referencia que nos d칠 m치s contexto sobre el problema que est치 experimentando.
      description: Puede adjuntar archivos arrastr치ndolos dentro del campo.
      render: markdown
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: 쯃e gustar칤a realizar un pull-request para esta caracter칤stica?
      options:
        - 'S칤 游'
        - 'No'
    validations:
      required: true
